language: node_js
node_js:
  - "8.11.2"

before_script:
  - cd sketch
  - yarn install

script:
  - yarn build
  - yarn test

cache:
  yarn: true
  directories:
  - node_modules
  - sketch/node_modules
