language: node_js
node_js:
  - "8.11.2"
services:
  - mongodb

before_script:
  - yarn install
  - yarn --cwd server install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug

script:
  - yarn build
  - yarn test
  - yarn --cwd server build
  - yarn --cwd server lint
  - yarn --cwd server test

after_script:
  - mv server/coverage .
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  yarn: true
  directories:
  - node_modules
  - server/node_modules

env:
  global:
    - CC_TEST_REPORTER_ID=654a8862c4f6aee42803f7759805fde13aa5dc419be37e0d901068df427372a9
