language: node_js
node_js:
  - "8.11.2"
services:
  - mongodb

before_script:
  - yarn install
  - yarn --cwd server install

script:
  - yarn build
  - yarn test
  - yarn --cwd server build
  - yarn --cwd server lint
  - yarn --cwd server test

cache:
  yarn: true
  directories:
  - node_modules
  - server/node_modules
